// misc
export const SETTING = 'SETTING'
export const USER_CONFIG = 'USER_CONFIG'
export const DASHBOARD = 'DASHBOARD'

// ROLE PERMISSION
export const ROLE_CREATE = 'ROLE_CREATE'
export const ROLE_UPDATE = 'ROLE_UPDATE'
export const ROLE_DELETE = 'ROLE_DELETE'
export const ROLE_LIST = 'ROLE_LIST'
export const ROLE_DETAILS = 'ROLE_DETAILS'

// PERMISSION
export const PERMISSION_CREATE = 'PERMISSION_CREATE'
export const PERMISSION_UPDATE = 'PERMISSION_UPDATE'
export const PERMISSION_DELETE = 'PERMISSION_DELETE'
export const PERMISSION_LIST = 'PERMISSION_LIST'
export const PERMISSION_DETAILS = 'PERMISSION_DETAILS'

// MENU_ITEM
export const MENU_ITEM_CREATE = 'MENU_ITEM_CREATE'
export const MENU_ITEM_UPDATE = 'MENU_ITEM_UPDATE'
export const MENU_ITEM_DELETE = 'MENU_ITEM_DELETE'
export const MENU_ITEM_LIST = 'MENU_ITEM_LIST'
export const MENU_ITEM_DETAILS = 'MENU_ITEM_DETAILS'

// ROLE_MENU
export const ROLE_MENU_CREATE = 'ROLE_MENU_CREATE'
export const ROLE_MENU_UPDATE = 'ROLE_MENU_UPDATE'
export const ROLE_MENU_DELETE = 'ROLE_MENU_DELETE'
export const ROLE_MENU_LIST = 'ROLE_MENU_LIST'
export const ROLE_MENU_DETAILS = 'ROLE_MENU_DETAILS'

// USER
export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_DELETE = 'USER_DELETE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAILS = 'USER_DETAILS'

// LOGIN_HISTORY
export const LOGIN_HISTORY_CREATE = 'LOGIN_HISTORY_CREATE'
export const LOGIN_HISTORY_UPDATE = 'LOGIN_HISTORY_UPDATE'
export const LOGIN_HISTORY_DELETE = 'LOGIN_HISTORY_DELETE'
export const LOGIN_HISTORY_LIST = 'LOGIN_HISTORY_LIST'
export const LOGIN_HISTORY_DETAILS = 'LOGIN_HISTORY_DETAILS'

// STATE
export const STATE_CREATE = 'STATE_CREATE'
export const STATE_UPDATE = 'STATE_UPDATE'
export const STATE_DELETE = 'STATE_DELETE'
export const STATE_LIST = 'STATE_LIST'
export const STATE_DETAILS = 'STATE_DETAILS'

// REGION
export const REGION_CREATE = 'REGION_CREATE'
export const REGION_UPDATE = 'REGION_UPDATE'
export const REGION_DELETE = 'REGION_DELETE'
export const REGION_LIST = 'REGION_LIST'
export const REGION_DETAILS = 'REGION_DETAILS'
